### ISSUE TITLE
Add and example of stoping the deploy if the zUnit test fails

### ISSUE THREAD

**Issue by RegiBrazil** [IBM/dbb-pipeline#10]
More details on slack https://ibm-systems-z.slack.com/archives/C2TBPA725/p1612533259046700?thread_ts=1610746163.014100&cid=C2TBPA725

**Comment by jbyibm** [comment]
Fixed by: https://github.com/IBM/dbb-pipeline/pull/11
If you have failing test cases the build will stop.

![image](https://user-images.githubusercontent.com/60784175/107539605-6a3c5400-6bc5-11eb-8825-329db60ead73.png)
