### ISSUE TITLE
Link to the tutorial pages

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-pipeline#15]
This repo is used within two tutorials - it would be worth mentioning that and create a link to them in the readme:

https://developer.ibm.com/tutorials/build-a-pipeline-with-gitlab-ci-dbb-and-ucd/
and
https://developer.ibm.com/tutorials/build-a-pipeline-with-jenkins-dependency-based-build-and-urbancode-deploy/

**Comment by jbyibm** [comment]
I have duplicated the README.md in `cics-genapp` into the  root folder.
