### ISSUE TITLE
New Copy Step fails if the package contains no CICS module

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-pipeline#2]
In case the _Generate Artifact Information_ step, returns an empty list, the _New Copy_ step fails.

It would be nice to work with a pre-condition in the new copy step like:

```
properties.get("GenLoadList/text") !== undefined &&
properties.get("GenLoadList/text") !== null &&
properties.get("GenLoadList/text") != ""
```

**Comment by jbyibm** [comment]
Thanks @dennis-behm

**Comment by jbyibm** [comment]
Fixed: https://github.com/IBM/dbb-pipeline/commit/d31a0650749f2e2e5003e8bb003862bab2d450e3
