### ISSUE TITLE
The userid and pwd of DBB Web Appl server must be externalized

### ISSUE THREAD

**Issue by RegiBrazil** [IBM/dbb-pipeline#3]
On the current paper the credentials are here: https://github.com/IBM/dbb-zappbuild/blob/development/build-conf/build.properties
They should be at the user repo.

**Comment by jbyibm** [comment]
We added an optional option in this document:  https://developer.ibm.com/components/ibmz/tutorials/build-a-pipeline-with-jenkins-dependency-based-build-and-urbancode-deploy/

![image](https://user-images.githubusercontent.com/60784175/102242528-6f00c680-3efa-11eb-96ac-8af99c05cd70.png)
